# Generated by Django 5.1.7 on 2025-03-14 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_create_initial_bt_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Boundary Item',
                'verbose_name_plural': 'Boundary Items',
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('formula', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
            },
        ),
        migrations.CreateModel(
            name='ESGFormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ESG Form Category',
                'verbose_name_plural': 'ESG Form Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ESGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('date_recorded', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('boundary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.boundaryitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.layerprofile')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESG Data',
                'verbose_name_plural': 'ESG Data',
            },
        ),
        migrations.CreateModel(
            name='DataEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('action', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('esg_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.esgdata')),
            ],
            options={
                'verbose_name': 'Data Edit Log',
                'verbose_name_plural': 'Data Edit Logs',
            },
        ),
        migrations.CreateModel(
            name='ESGForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='data_management.esgformcategory')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ESGMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('kWh', 'Kilowatt Hours'), ('MWh', 'Megawatt Hours'), ('m3', 'Cubic Meters'), ('tonnes', 'Tonnes'), ('tCO2e', 'Tonnes CO2 Equivalent'), ('person', 'Person'), ('hours', 'Hours'), ('days', 'Days'), ('count', 'Count'), ('percentage', 'Percentage'), ('custom', 'Custom Unit')], max_length=20)),
                ('custom_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(choices=[('HK', 'Hong Kong'), ('PRC', 'Mainland China'), ('ALL', 'All Locations')], default='ALL', max_length=3)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this metric must be reported')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='data_management.esgform')),
            ],
            options={
                'ordering': ['form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reporting_period', models.CharField(help_text="e.g., 'Annual 2024', 'Q1 2024'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.layerprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFormSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.esgform')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.template')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='selected_forms',
            field=models.ManyToManyField(through='data_management.TemplateFormSelection', to='data_management.esgform'),
        ),
        migrations.AddIndex(
            model_name='esgdata',
            index=models.Index(fields=['company', 'date_recorded'], name='data_manage_company_043466_idx'),
        ),
        migrations.AddIndex(
            model_name='esgdata',
            index=models.Index(fields=['scope'], name='data_manage_scope_f99b68_idx'),
        ),
        migrations.AddIndex(
            model_name='esgform',
            index=models.Index(fields=['code'], name='data_manage_code_2af201_idx'),
        ),
        migrations.AddIndex(
            model_name='esgform',
            index=models.Index(fields=['is_active'], name='data_manage_is_acti_12a29a_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['template', 'company'], name='data_manage_templat_1dca89_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['assigned_to'], name='data_manage_assigne_e7a3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['due_date'], name='data_manage_due_dat_2de6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['status'], name='data_manage_status_b7252d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateformselection',
            unique_together={('template', 'form')},
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='data_manage_is_acti_ce9fe6_idx'),
        ),
    ]
