# Generated by Django 5.1.7 on 2025-03-16 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_remove_esgdata_data_manage_company_043466_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGMetricSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, help_text='For non-numeric metrics', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='data_management.templateassignment')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.esgmetric')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_submissions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESGMetricEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='esg_evidence/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='data_management.esgmetricsubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['assignment', 'metric'], name='data_manage_assignm_675d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['submitted_by'], name='data_manage_submitt_023da3_idx'),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['is_verified'], name='data_manage_is_veri_0b2fd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='esgmetricsubmission',
            unique_together={('assignment', 'metric')},
        ),
    ]
