# Generated by Django 5.1.7 on 2025-03-16 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_esgmetricsubmission_esgmetricevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esgmetricsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], help_text='Required frequency of reporting for time-based metrics', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='requires_time_reporting',
            field=models.BooleanField(default=False, help_text='Whether this metric requires reporting for multiple time periods'),
        ),
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='reporting_period',
            field=models.DateField(blank=True, help_text='For time-based metrics (e.g., monthly data)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='esgmetricsubmission',
            unique_together={('assignment', 'metric', 'reporting_period')},
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['reporting_period'], name='data_manage_reporti_837239_idx'),
        ),
    ]
