# Generated by Django 5.1.7 on 2025-03-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_alter_esgmetricsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='reporting_period',
        ),
    ]
