# Generated by Django 5.1.7 on 2025-03-17 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_remove_template_reporting_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templateformselection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateformselection',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateformselection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
