# Generated by Django 5.1.7 on 2025-03-22 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_templateformselection_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When the OCR result was edited', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='Who edited the OCR result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='extracted_period',
            field=models.DateField(blank=True, help_text='Reporting period extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='extracted_value',
            field=models.FloatField(blank=True, help_text='Value extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='is_utility_bill',
            field=models.BooleanField(default=False, help_text='Whether this evidence is a utility bill for OCR processing'),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='ocr_data',
            field=models.JSONField(blank=True, help_text='Raw data extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='ocr_processed',
            field=models.BooleanField(default=False, help_text='Whether OCR processing has been attempted'),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='was_manually_edited',
            field=models.BooleanField(default=False, help_text='Whether the OCR result was manually edited'),
        ),
    ]
