# Generated by Django 5.1.7 on 2025-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_esgmetricevidence_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetric',
            name='ocr_analyzer_id',
            field=models.CharField(blank=True, help_text="Custom analyzer ID for OCR processing of this metric's evidence", max_length=100, null=True),
        ),
    ]
