# Generated by Django 5.1.7 on 2025-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_esgmetric_ocr_analyzer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetricevidence',
            name='is_utility_bill',
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='enable_ocr_processing',
            field=models.BooleanField(default=False, help_text='User option to enable OCR data extraction for this evidence file'),
        ),
    ]
