# Generated by Django 5.1.7 on 2025-03-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_rename_ocr_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esgmetricevidence',
            old_name='ocr_processed',
            new_name='is_processed_by_ocr',
        ),
        migrations.RenameField(
            model_name='esgmetricevidence',
            old_name='extracted_period',
            new_name='period',
        ),
    ]
