# Generated by Django 5.1.7 on 2025-03-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_rename_evidence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgmetricevidence',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Can be null for standalone evidence files before attaching to a submission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='data_management.esgmetricsubmission'),
        ),
    ]
