# Generated by Django 5.1.7 on 2025-03-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_add_standalone_evidence_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='intended_metric',
            field=models.ForeignKey(blank=True, help_text='The metric this evidence is intended for, before being attached to a submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_evidence', to='data_management.esgmetric'),
        ),
    ]
