# Generated by Django 5.1.7 on 2025-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_esgmetricevidence_intended_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateassignment',
            name='reporting_year',
            field=models.PositiveIntegerField(default=2025, help_text='The year this reporting data represents (e.g., 2024)'),
        ),
    ]
