# Generated by Django 5.1.7 on 2025-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_esgmetricevidence_ocr_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgmetricevidence',
            name='enable_ocr_processing',
            field=models.BooleanField(default=True, help_text='Whether OCR processing is available for this evidence file'),
        ),
    ]
