# Generated by Django 5.1.7 on 2025-03-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0017_add_layer_to_models'),
    ]

    operations = [
    ]
