# Generated by Django 5.1.7 on 2025-03-30 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_layerprofile_created_by_admin'),
        ('data_management', '0019_update_existing_layer_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGMetricBatchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this batch', max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSchemaRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='JSON Schema definition for this metric type')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Metric Schema',
                'verbose_name_plural': 'Metric Schemas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='esgmetricsubmission',
            name='data_manage_reporti_837239_idx',
        ),
        migrations.AlterUniqueTogether(
            name='esgmetricsubmission',
            unique_together={('assignment', 'metric', 'layer')},
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='data_schema',
            field=models.JSONField(blank=True, default=dict, help_text="JSON Schema for this metric's data"),
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='form_component',
            field=models.CharField(blank=True, help_text='Frontend component to use for this metric', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Structured data extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='reference_path',
            field=models.CharField(blank=True, help_text="JSON path this evidence relates to (e.g., 'periods.Jan-2024')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='data',
            field=models.JSONField(blank=True, help_text='All metric data in structured JSON format', null=True),
        ),
        migrations.AddField(
            model_name='esgmetricbatchsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_submissions', to='data_management.templateassignment'),
        ),
        migrations.AddField(
            model_name='esgmetricbatchsubmission',
            name='layer',
            field=models.ForeignKey(blank=True, help_text="The layer this submission's data represents", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_submissions', to='accounts.layerprofile'),
        ),
        migrations.AddField(
            model_name='esgmetricbatchsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgmetricbatchsubmission',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='batch_submission',
            field=models.ForeignKey(blank=True, help_text='Batch this submission belongs to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='data_management.esgmetricbatchsubmission'),
        ),
        migrations.AddField(
            model_name='metricschemaregistry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='schema_registry',
            field=models.ForeignKey(blank=True, help_text='Reference to a registered schema for this metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='data_management.metricschemaregistry'),
        ),
    ]
