# Generated by Django 5.1.7 on 2025-04-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_update_existing_layer_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetric',
            name='is_multi_value',
            field=models.BooleanField(default=False, help_text='Whether this metric requires multiple related values'),
        ),
        migrations.CreateModel(
            name='MetricValueField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Unique identifier for this field', max_length=50)),
                ('display_name', models.CharField(help_text='User-friendly name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('column_header', models.CharField(blank=True, help_text="For tabular display (e.g., 'A', 'B')", max_length=50)),
                ('display_type', models.CharField(choices=[('TEXT', 'Text Input'), ('NUMBER', 'Number Input'), ('SELECT', 'Dropdown Selection')], default='NUMBER', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='Options for dropdown fields', null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_fields', to='data_management.esgmetric')),
            ],
            options={
                'ordering': ['metric', 'order'],
                'unique_together': {('metric', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_values', to='data_management.esgmetricsubmission')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.metricvaluefield')),
            ],
            options={
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
