# Generated by Django 5.1.7 on 2025-04-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_metric_value_perms'),
        ('data_management', '0021_alter_esgmetricsubmission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedMetricFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregated_numeric_value', models.FloatField(blank=True, null=True)),
                ('aggregated_text_value', models.TextField(blank=True, null=True)),
                ('aggregation_method', models.CharField(default='SUM', help_text='Method used (e.g., SUM, AVERAGE, LAST)', max_length=20)),
                ('source_submission_count', models.PositiveIntegerField(default=0, help_text="Number of source submissions contributing to this field's aggregation")),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aggregated Metric Field Value',
                'verbose_name_plural': 'Aggregated Metric Field Values',
            },
        ),
        migrations.AlterModelOptions(
            name='reportedmetricvalue',
            options={'ordering': ['assignment', 'metric', 'reporting_period'], 'verbose_name': 'Aggregated Metric Record', 'verbose_name_plural': 'Aggregated Metric Records'},
        ),
        migrations.RemoveIndex(
            model_name='esgmetricsubmission',
            name='data_manage_reporte_e80618_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportedmetricvalue',
            name='data_manage_is_veri_a8c6e8_idx',
        ),
        migrations.RenameIndex(
            model_name='reportedmetricvalue',
            new_name='unique_agg_record_idx',
            old_name='unique_reported_value_idx',
        ),
        migrations.RemoveField(
            model_name='esgmetricsubmission',
            name='reported_value',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='reportedmetricvalue',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='aggregated_numeric_value',
            field=models.FloatField(blank=True, help_text='Aggregated value if the input metric is single-value numeric', null=True),
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='aggregated_text_value',
            field=models.TextField(blank=True, help_text='Aggregated value if the input metric is single-value text', null=True),
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='first_submission_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first submission included', null=True),
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='last_submission_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last submission included', null=True),
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='source_submission_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of source submissions contributing to this aggregation'),
        ),
        migrations.AlterField(
            model_name='esgmetricsubmission',
            name='text_value',
            field=models.TextField(blank=True, help_text='Raw value for single-value text metrics', null=True),
        ),
        migrations.AlterField(
            model_name='esgmetricsubmission',
            name='value',
            field=models.FloatField(blank=True, help_text='Raw value for single-value numeric metrics', null=True),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_records', to='data_management.templateassignment'),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was first created'),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record or its fields were last updated by aggregation'),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_records', to='accounts.layerprofile'),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_records', to='data_management.esgmetric'),
        ),
        migrations.AddField(
            model_name='reportedmetricfieldvalue',
            name='field',
            field=models.ForeignKey(help_text='The specific field definition from the input metric', on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_field_values', to='data_management.metricvaluefield'),
        ),
        migrations.AddField(
            model_name='reportedmetricfieldvalue',
            name='reported_value',
            field=models.ForeignKey(help_text='Parent aggregation record', on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_fields', to='data_management.reportedmetricvalue'),
        ),
        migrations.AddIndex(
            model_name='reportedmetricfieldvalue',
            index=models.Index(fields=['reported_value', 'field'], name='data_manage_reporte_eba09a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportedmetricfieldvalue',
            unique_together={('reported_value', 'field')},
        ),
    ]
