# Generated by Django 5.1.7 on 2025-03-30 12:49

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_layerprofile_created_by_admin'),
        ('data_management', '0022_remove_unit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='esgmetricsubmission',
            name='data_gin_idx',
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], help_text='Reporting frequency, only used for time-based metrics', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='requires_time_reporting',
            field=models.BooleanField(default=False, help_text='Whether this metric requires time-based reporting (e.g., quarterly, monthly)'),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=GinIndex(fields=['data'], name='data_gin_idx', opclasses=['jsonb_path_ops']),
        ),
    ]
