# Generated by Django 5.1.7 on 2025-04-04 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_metric_value_perms'),
        ('data_management', '0022_reportedmetricfieldvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='source_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Optional identifier for the source of this input (e.g., meter ID, specific file)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['source_identifier'], name='data_manage_source__e1c0ae_idx'),
        ),
    ]
