# Generated by Django 5.1.7 on 2025-03-30 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_metricschemaregistry_permissions'),
        ('data_management', '0024_add_schema_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='esgmetricsubmission',
            name='data_gin_idx',
        ),
        migrations.AlterUniqueTogether(
            name='esgmetricsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='submission_identifier',
            field=models.CharField(blank=True, default='', help_text='Identifier to match with a specific submission', max_length=255),
        ),
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='data_source',
            field=models.CharField(blank=True, default='', help_text="Source of the data (e.g., 'Invoice', 'Meter Reading', 'Estimate')", max_length=255),
        ),
        migrations.AddField(
            model_name='esgmetricsubmission',
            name='submission_identifier',
            field=models.CharField(blank=True, default='', help_text='Optional identifier to distinguish multiple submissions for the same metric/layer', max_length=255),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['data'], name='data_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['submission_identifier'], name='data_manage_submiss_49d189_idx'),
        ),
        migrations.AddIndex(
            model_name='esgmetricsubmission',
            index=models.Index(fields=['assignment', 'metric', 'layer', 'submission_identifier'], name='data_manage_assignm_95bf86_idx'),
        ),
    ]
