# Generated by Django 5.1.7 on 2025-04-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0024_baseesgmetric_basicmetric_and_more'),
    ]

    operations = [
    ]
