# Generated by Django 5.1.7 on 2025-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0025_remove_esgmetricsubmission_data_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='json_path',
            field=models.CharField(blank=True, help_text="JSON path this evidence supports in the submission's data structure", max_length=255, null=True),
        ),
    ]
