# Generated by Django 5.1.7 on 2025-04-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0025_migrate_esg_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgmetricsubmission',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.baseesgmetric'),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_records', to='data_management.baseesgmetric'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvaluefield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metricvaluefield',
            name='metric',
        ),
        migrations.AlterField(
            model_name='esgmetricevidence',
            name='intended_metric',
            field=models.ForeignKey(blank=True, help_text='The metric this evidence is intended for, before being attached to a submission input', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_evidence', to='data_management.baseesgmetric'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metricvalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='metricvalue',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='reportedmetricfieldvalue',
            name='field',
        ),
        migrations.AlterField(
            model_name='esgmetricsubmission',
            name='text_value',
            field=models.TextField(blank=True, help_text='Raw value for single-value text metrics (legacy/basic)', null=True),
        ),
        migrations.AlterField(
            model_name='esgmetricsubmission',
            name='value',
            field=models.FloatField(blank=True, help_text='Raw value for single-value numeric metrics (legacy/basic)', null=True),
        ),
        migrations.DeleteModel(
            name='ESGMetric',
        ),
        migrations.DeleteModel(
            name='MetricValue',
        ),
        migrations.DeleteModel(
            name='MetricValueField',
        ),
        migrations.DeleteModel(
            name='ReportedMetricFieldValue',
        ),
    ]
