# Generated by Django 5.1.7 on 2025-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0026_esgmetricevidence_json_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='supports_multiple_periods',
            field=models.BooleanField(default=False, help_text='Indicates this evidence supports multiple periods or values across different paths'),
        ),
        migrations.AlterField(
            model_name='esgmetricevidence',
            name='reference_path',
            field=models.CharField(blank=True, help_text="JSON path this evidence relates to in the submission's data structure (e.g., 'periods.Jan-2024')", max_length=255, null=True),
        ),
    ]
