# Generated by Django 5.1.7 on 2025-04-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0026_alter_esgmetricsubmission_metric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetricsubmission',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='esgmetricsubmission',
            name='value',
        ),
        migrations.CreateModel(
            name='BasicMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.FloatField(blank=True, help_text='Submitted numeric value', null=True)),
                ('value_text', models.TextField(blank=True, help_text='Submitted text value', null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_data', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Basic Metric Data',
                'verbose_name_plural': 'Basic Metric Data',
            },
        ),
        migrations.CreateModel(
            name='MultiFieldDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.JSONField(default=dict, help_text='Key-value pairs for the fields')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multifield_data', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Multi-Field Data Point',
                'verbose_name_plural': 'Multi-Field Data Points',
            },
        ),
        migrations.CreateModel(
            name='MaterialMatrixDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(help_text='Name of the material type (e.g., Cardboard)', max_length=100)),
                ('period', models.DateField(help_text='The period this data point represents (e.g., month end)')),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit used for this specific data point (if overrides default)', max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_data_points', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Material Matrix Data Point',
                'verbose_name_plural': 'Material Matrix Data Points',
                'ordering': ['submission', 'period', 'material_type'],
                'unique_together': {('submission', 'period', 'material_type')},
            },
        ),
        migrations.CreateModel(
            name='MultiFieldTimeSeriesDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='The specific period this row of data represents')),
                ('field_data', models.JSONField(default=dict, help_text='Key-value pairs for the fields in this period')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multifield_timeseries_data_points', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Multi-Field Time Series Data Point',
                'verbose_name_plural': 'Multi-Field Time Series Data Points',
                'ordering': ['submission', 'period'],
                'unique_together': {('submission', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TabularMetricRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Order of the row within the submission')),
                ('row_data', models.JSONField(default=dict, help_text='Key-value pairs for the columns in this row')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabular_rows', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Tabular Metric Row',
                'verbose_name_plural': 'Tabular Metric Rows',
                'ordering': ['submission', 'row_index'],
                'unique_together': {('submission', 'row_index')},
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='The specific period this data point represents')),
                ('value', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_data_points', to='data_management.esgmetricsubmission')),
            ],
            options={
                'verbose_name': 'Time Series Data Point',
                'verbose_name_plural': 'Time Series Data Points',
                'ordering': ['submission', 'period'],
                'unique_together': {('submission', 'period')},
            },
        ),
    ]
