# Generated by Django 5.1.7 on 2025-04-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_metric_value_perms'),
        ('data_management', '0027_remove_esgmetricsubmission_text_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedmetricvalue',
            options={'ordering': ['assignment', 'metric', 'reporting_period', 'level'], 'verbose_name': 'Aggregated Metric Record', 'verbose_name_plural': 'Aggregated Metric Records'},
        ),
        migrations.RemoveIndex(
            model_name='reportedmetricvalue',
            name='unique_agg_record_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reportedmetricvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportedmetricvalue',
            name='level',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annual')], default='A', help_text='Aggregation level (Monthly, Quarterly, Annual)', max_length=1),
        ),
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='reporting_period',
            field=models.DateField(help_text='End date of the period this aggregated value represents'),
        ),
        migrations.AlterUniqueTogether(
            name='reportedmetricvalue',
            unique_together={('assignment', 'metric', 'reporting_period', 'layer', 'level')},
        ),
        migrations.AddIndex(
            model_name='reportedmetricvalue',
            index=models.Index(fields=['assignment', 'metric', 'reporting_period', 'layer', 'level'], name='unique_agg_record_lvl_idx'),
        ),
        migrations.AddIndex(
            model_name='reportedmetricvalue',
            index=models.Index(fields=['level'], name='data_manage_level_3d5398_idx'),
        ),
    ]
