# Generated by Django 5.1.7 on 2025-03-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0027_esgmetricevidence_supports_multiple_periods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetricevidence',
            name='json_path',
        ),
    ]
