# Generated by Django 5.1.7 on 2025-04-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0028_alter_reportedmetricvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmetricvalue',
            name='level',
            field=models.CharField(choices=[('M', 'Monthly'), ('A', 'Annual')], default='A', help_text='Aggregation level (Monthly, Quarterly, Annual)', max_length=1),
        ),
    ]
