# Generated by Django 5.1.7 on 2025-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0028_remove_esgmetricevidence_json_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetricsubmission',
            name='data_source',
        ),
        migrations.AddField(
            model_name='esgmetricevidence',
            name='source_type',
            field=models.CharField(choices=[('UTILITY_BILL', 'Utility Bill'), ('METER_READING', 'Meter Reading'), ('INVOICE', 'Invoice'), ('ESTIMATE', 'Estimate'), ('AUDIT_REPORT', 'Audit Report'), ('THIRD_PARTY', 'Third-party Verification'), ('INTERNAL', 'Internal Assessment'), ('OTHER', 'Other')], default='OTHER', help_text='Type of source document this evidence represents', max_length=30),
        ),
    ]
