# Generated by Django 5.1.7 on 2025-03-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0029_remove_esgmetricsubmission_data_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetric',
            name='data_schema',
        ),
        migrations.RemoveField(
            model_name='esgmetric',
            name='schema_type',
        ),
    ]
