# Generated by Django 5.1.7 on 2025-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0029_remove_esgmetricsubmission_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgmetric',
            name='data_schema',
            field=models.JSONField(blank=True, default=dict, help_text="JSON Schema for this metric's data. Only used if no Schema Registry entry is selected. Schema Registry takes precedence if both are provided."),
        ),
        migrations.AlterField(
            model_name='esgmetric',
            name='schema_type',
            field=models.CharField(blank=True, help_text="Direct reference to schema type (e.g., 'electricity_hk', 'electricity_prc'). Optional and only used if schema_registry is not selected.", max_length=50, null=True),
        ),
    ]
