# Generated by Django 5.1.7 on 2025-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0029_alter_reportedmetricvalue_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseesgmetric',
            name='allow_multiple_submissions_per_period',
            field=models.BooleanField(default=False, help_text='Allow multiple submission records for the same assignment, metric, and reporting period? (Set True for metrics expecting data from multiple sources per period, like TimeSeries from different facilities)'),
        ),
    ]
