# Generated by Django 5.1.7 on 2025-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0030_baseesgmetric_allow_multiple_submissions_per_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseesgmetric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseesgmetric',
            name='help_text',
            field=models.TextField(blank=True, help_text='Optional guidance text displayed to the user in the form', null=True),
        ),
    ]
