# Generated by Django 5.1.7 on 2025-03-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0030_remove_esgmetric_data_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetric',
            name='validation_rules',
        ),
    ]
