# Generated by Django 5.1.7 on 2025-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0032_baseesgmetric_emission_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='source_identifier',
            field=models.CharField(blank=True, help_text='Identifier for the source of this evidence when metric allows multiple submissions (e.g., facility name)', max_length=100, null=True),
        ),
    ]
