# Generated by Django 5.1.7 on 2025-04-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0033_esgmetricevidence_source_identifier_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE data_management_esgmetricsubmission DROP COLUMN IF EXISTS contribution_verification_status;",
            reverse_sql="ALTER TABLE data_management_esgmetricsubmission ADD COLUMN contribution_verification_status varchar(20) DEFAULT 'UNVERIFIED';"
        ),
    ]
