# Generated by Django 5.1.7 on 2025-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0034_remove_contribution_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetricevidence',
            name='submission',
        ),
    ] 