# Generated by Django 5.1.7 on 2025-04-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0036_vehicledatasource_vehiclemonthlydata_vehiclerecord_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculatedemissionvalue',
            unique_together={('source_activity_value', 'emission_factor', 'related_group_id', 'is_primary_record')},
        ),
    ]
