# Generated by Django 5.1.7 on 2025-04-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0037_alter_calculatedemissionvalue_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Unique identifier code for this fuel type', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display name for this fuel type', max_length=255)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Unique identifier code for this vehicle type', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display name for this vehicle type', max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='fuel_type_code',
            field=models.CharField(blank=True, help_text='DEPRECATED: Legacy fuel type code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='vehicle_type_code',
            field=models.CharField(blank=True, help_text='DEPRECATED: Legacy vehicle type code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletrackingmetric',
            name='fuel_type_choices',
            field=models.JSONField(default=list, help_text='DEPRECATED: Use fuel_types M2M relation instead'),
        ),
        migrations.AlterField(
            model_name='vehicletrackingmetric',
            name='vehicle_type_choices',
            field=models.JSONField(default=list, help_text='DEPRECATED: Use vehicle_types M2M relation instead'),
        ),
        migrations.AddField(
            model_name='vehicletrackingmetric',
            name='fuel_types',
            field=models.ManyToManyField(help_text='Fuel types available for selection', related_name='metrics', to='data_management.fueltype'),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='fuel_type',
            field=models.ForeignKey(help_text='Type of fuel used (e.g., petrol, diesel)', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='data_management.fueltype'),
        ),
        migrations.AddField(
            model_name='vehicletrackingmetric',
            name='vehicle_types',
            field=models.ManyToManyField(help_text='Vehicle types available for selection', related_name='metrics', to='data_management.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='vehicle_type',
            field=models.ForeignKey(help_text='Type of vehicle (e.g., private car, truck)', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='data_management.vehicletype'),
        ),
    ]
