# Generated by Django 5.1.7 on 2025-04-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_additional_admin_permissions'),
        ('data_management', '0038_fueltype_vehicletype_vehiclerecord_fuel_type_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculatedemissionvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vehiclerecord',
            name='fuel_type_code',
        ),
        migrations.RemoveField(
            model_name='vehiclerecord',
            name='vehicle_type_code',
        ),
        migrations.AddField(
            model_name='calculatedemissionvalue',
            name='vehicle_record',
            field=models.ForeignKey(blank=True, help_text='For vehicle emissions, the specific vehicle this calculation applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_calculations', to='data_management.vehiclerecord'),
        ),
        migrations.AlterUniqueTogether(
            name='calculatedemissionvalue',
            unique_together={('source_activity_value', 'emission_factor', 'related_group_id', 'is_primary_record', 'vehicle_record')},
        ),
        migrations.AddIndex(
            model_name='calculatedemissionvalue',
            index=models.Index(fields=['vehicle_record'], name='data_manage_vehicle_54c441_idx'),
        ),
    ]
