# Generated by Django 5.1.7 on 2025-04-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0039_alter_calculatedemissionvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgmetricevidence',
            name='target_vehicle',
            field=models.ForeignKey(blank=True, help_text='The specific vehicle this evidence relates to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_files', to='data_management.vehiclerecord'),
        ),
    ]
