# Generated by Django 5.1.7 on 2025-04-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0041_fuelsourcetype_fuelrecord_fuelmonthlydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationaryFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Unique identifier code for this stationary fuel type', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display name for this stationary fuel type', max_length=255)),
                ('unit', models.CharField(default='litre', help_text='Unit of measurement for this fuel type', max_length=50)),
            ],
            options={
                'verbose_name': 'Stationary Fuel Type',
                'verbose_name_plural': 'Stationary Fuel Types',
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='fuelconsumptionmetric',
            name='fuel_types',
            field=models.ManyToManyField(help_text='Fuel types available for selection', related_name='fuel_consumption_metrics', to='data_management.stationaryfueltype'),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='fuel_type',
            field=models.ForeignKey(help_text='Type of fuel used (e.g., diesel, natural gas)', on_delete=django.db.models.deletion.PROTECT, related_name='fuel_sources', to='data_management.stationaryfueltype'),
        ),
    ]
