# Generated by Django 5.1.7 on 2025-04-17 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_fuel_model_permissions'),
        ('data_management', '0042_stationaryfueltype_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculatedemissionvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calculatedemissionvalue',
            name='fuel_record',
            field=models.ForeignKey(blank=True, help_text='For fuel emissions, the specific fuel record this calculation applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_calculations', to='data_management.fuelrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='calculatedemissionvalue',
            unique_together={('source_activity_value', 'emission_factor', 'related_group_id', 'is_primary_record', 'vehicle_record', 'fuel_record')},
        ),
        migrations.AddIndex(
            model_name='calculatedemissionvalue',
            index=models.Index(fields=['fuel_record'], name='data_manage_fuel_re_5e2dcf_idx'),
        ),
    ]
