# Generated by Django 5.1.7 on 2025-04-23 16:20

from django.db import migrations

def update_checklist_metrics(apps, schema_editor):
    # Get the historical version of the ChecklistMetric model
    ChecklistMetric = apps.get_model('data_management', 'ChecklistMetric')
    
    # Update all existing ChecklistMetric instances
    updated = ChecklistMetric.objects.update(aggregates_inputs=False)
    
    print(f"Updated {updated} ChecklistMetric instances to set aggregates_inputs=False")

class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0045_checklistmetric_checklistreport_checklistresponse'),
    ]

    operations = [
        migrations.RunPython(update_checklist_metrics, migrations.RunPython.noop),
    ]
