# Generated by Django 5.1.7 on 2025-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0046_update_checklist_aggregates_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistreport',
            name='is_structured',
            field=models.BooleanField(default=False, help_text='Whether the content field contains structured JSON data'),
        ),
        migrations.AlterField(
            model_name='checklistreport',
            name='content',
            field=models.TextField(help_text='The full text or JSON content of the AI-generated report'),
        ),
    ]
