# Generated by Django 5.1.7 on 2025-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0047_checklistreport_is_structured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistreport',
            name='esg_rating',
            field=models.CharField(blank=True, help_text='Overall ESG rating (A-F)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='checklistreport',
            name='rating_description',
            field=models.CharField(blank=True, help_text='Description of the ESG rating', max_length=255, null=True),
        ),
    ]
