# Generated by Django 5.1.7 on 2025-04-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0048_checklistreport_esg_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateformselection',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED - Use FormCompletionStatus instead', null=True),
        ),
        migrations.AlterField(
            model_name='templateformselection',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - Use FormCompletionStatus instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templateformselection',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='DEPRECATED - Use FormCompletionStatus instead'),
        ),
        migrations.CreateModel(
            name='FormCompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(help_text='The template assignment this completion status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='form_completion_status', to='data_management.templateassignment')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_assignment_forms', to=settings.AUTH_USER_MODEL)),
                ('form_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_completion', to='data_management.templateformselection')),
            ],
            options={
                'verbose_name': 'Form Completion Status',
                'verbose_name_plural': 'Form Completion Statuses',
                'ordering': ['assignment', 'form_selection'],
                'indexes': [models.Index(fields=['form_selection', 'assignment'], name='data_manage_form_se_37140f_idx'), models.Index(fields=['is_completed'], name='data_manage_is_comp_7c8260_idx'), models.Index(fields=['assignment'], name='data_manage_assignm_9a0330_idx')],
                'unique_together': {('form_selection', 'assignment')},
            },
        ),
    ]
