# Generated by Django 5.1.7 on 2025-05-25 20:51

import data_management.models.templates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0050_formcompletionstatus_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmetric',
            name='unit_type',
            field=models.CharField(choices=[('kWh', 'Kilowatt Hours'), ('MWh', 'Megawatt Hours'), ('m3', 'Cubic Meters'), ('tonnes', 'Tonnes'), ('kg', 'Kilograms'), ('tCO2e', 'Tonnes CO2 Equivalent'), ('MJ', 'Megajoules'), ('person', 'Person'), ('hours', 'Hours'), ('days', 'Days'), ('count', 'Count'), ('percentage', 'Percentage'), ('text', 'Text'), ('custom', 'Custom Unit')], default='count', help_text='The type of unit this metric uses', max_length=20),
        ),
        migrations.AlterField(
            model_name='esgmetricevidence',
            name='file',
            field=models.FileField(upload_to=data_management.models.templates.ESGMetricEvidence.evidence_upload_to),
        ),
        migrations.AlterField(
            model_name='timeseriesmetric',
            name='unit_type',
            field=models.CharField(choices=[('kWh', 'Kilowatt Hours'), ('MWh', 'Megawatt Hours'), ('m3', 'Cubic Meters'), ('tonnes', 'Tonnes'), ('kg', 'Kilograms'), ('tCO2e', 'Tonnes CO2 Equivalent'), ('MJ', 'Megajoules'), ('person', 'Person'), ('hours', 'Hours'), ('days', 'Days'), ('count', 'Count'), ('percentage', 'Percentage'), ('text', 'Text'), ('custom', 'Custom Unit')], default='count', max_length=20),
        ),
    ]
