# Generated by Django 5.1.7 on 2025-06-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_layerprofile_annual_revenue_and_more'),
        ('data_management', '0051_alter_basicmetric_unit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formcompletionstatus',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin has verified this completed form'),
        ),
        migrations.AddField(
            model_name='formcompletionstatus',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes during verification process'),
        ),
        migrations.AddField(
            model_name='formcompletionstatus',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the admin verified this form', null=True),
        ),
        migrations.AddField(
            model_name='formcompletionstatus',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formcompletionstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user marked this form as complete', null=True),
        ),
        migrations.AlterField(
            model_name='formcompletionstatus',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='User has marked this form as complete'),
        ),
        migrations.AddIndex(
            model_name='formcompletionstatus',
            index=models.Index(fields=['is_verified'], name='data_manage_is_veri_294ffa_idx'),
        ),
    ]
