# Generated by Django 5.1.7 on 2025-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0052_add_form_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcompletionstatus',
            name='revision_required',
            field=models.BooleanField(default=False, help_text='Admin has sent this form back for revision'),
        ),
    ]
