# Generated by Django 5.1.7 on 2025-03-12 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_industry', models.CharField(max_length=100)),
                ('shareholding_ratio', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('layer_type', models.CharField(choices=[('GROUP', 'Group'), ('SUBSIDIARY', 'Subsidiary'), ('BRANCH', 'Branch')], max_length=20)),
                ('company_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Layer',
                'verbose_name_plural': 'Company Layers',
            },
        ),
        migrations.CreateModel(
            name='CSVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('default', 'Default'), ('superuser', 'Superuser'), ('appuser', 'App User')], default='default', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSV Template',
                'verbose_name_plural': 'CSV Templates',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('reset_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('MANAGEMENT', 'Management'), ('OPERATION', 'Operation')], default='OPERATION', max_length=20)),
                ('is_baker_tilly_admin', models.BooleanField(default=False, help_text='Designates whether this user is a Baker Tilly administrator with access to all client data.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupLayer',
            fields=[
                ('layerprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.layerprofile')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=('accounts.layerprofile',),
        ),
        migrations.CreateModel(
            name='SubsidiaryLayer',
            fields=[
                ('layerprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.layerprofile')),
                ('group_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grouplayer')),
            ],
            options={
                'verbose_name': 'Subsidiary',
                'verbose_name_plural': 'Subsidiaries',
            },
            bases=('accounts.layerprofile',),
        ),
        migrations.CreateModel(
            name='BranchLayer',
            fields=[
                ('layerprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.layerprofile')),
                ('subsidiary_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subsidiarylayer')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
            bases=('accounts.layerprofile',),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_users', to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_users', to='accounts.layerprofile')),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'unique_together': {('user', 'layer')},
            },
        ),
    ]
