# Generated by Django 5.1.7 on 2025-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_fuel_model_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerprofile',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue in millions', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='layerprofile',
            name='company_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of employees', null=True),
        ),
        migrations.AddField(
            model_name='layerprofile',
            name='number_of_sites',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sites/entities', null=True),
        ),
        migrations.AddField(
            model_name='layerprofile',
            name='target_customer',
            field=models.TextField(blank=True, help_text='Description of target customers', null=True),
        ),
    ]
